# Generated by Django 3.2 on 2022-12-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('company_id', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.CharField(max_length=200)),
                ('predict', models.FloatField()),
                ('feel', models.BooleanField()),
            ],
        ),
    ]
