# Generated by Django 3.2 on 2023-01-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0002_alter_emotion_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotion',
            name='user_id',
        ),
    ]
