# Generated by Django 3.2 on 2023-01-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0003_remove_emotion_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
