# Generated by Django 3.2 on 2023-01-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='workers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
